version: '3'

services:
  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=snow_db
  web:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    postgres_data: