# development docker-compose file
# not for production, use prod.docker-compose.yml for production
version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: snow_db
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/:ro'
      - my-datavolume:/var/lib/mysql

  backend:
    image: backend
    restart: always
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - 7081
    volumes:
      - './backend:/app'
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      
  nginx:
    image: snowdata-nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: snowdata-nginx
    restart: always
    ports:
      - '7082:7082'

# allows for persistent db volumes
volumes:
  my-datavolume:

# nginx connects to backend
# backend exposes 7081, nginx passes that port to 7082
# frontend acceses backend by POST req to localhost:7082